<?php
$env_items = array();
$dirfile_items = array(
		array('type' => 'dir', 'path' => 'data/cache'),
		array('type' => 'dir', 'path' => 'data/cache/adv'),
		array('type' => 'dir', 'path' => 'data/cache/rec_position'),
		array('type' => 'dir', 'path' => 'data/config'),
		array('type' => 'dir', 'path' => 'data/log'),
		array('type' => 'dir', 'path' => 'data/session'),
		array('type' => 'dir', 'path' => 'data/resource/phpqrcode/temp'),
		array('type' => 'dir', 'path' => 'data/upload'),
		array('type' => 'dir', 'path' => 'data/upload/shop/activity'),
		array('type' => 'dir', 'path' => 'data/upload/shop/adv'),
		array('type' => 'dir', 'path' => 'data/upload/shop/article'),
		array('type' => 'dir', 'path' => 'data/upload/shop/avatar'),
		array('type' => 'dir', 'path' => 'data/upload/shop/brand'),
		array('type' => 'dir', 'path' => 'data/upload/shop/common'),
		array('type' => 'dir', 'path' => 'data/upload/shop/complain'),
		array('type' => 'dir', 'path' => 'data/upload/shop/editor'),
		array('type' => 'dir', 'path' => 'data/upload/shop/groupbuy'),
		array('type' => 'dir', 'path' => 'data/upload/shop/inform'),
		array('type' => 'dir', 'path' => 'data/upload/shop/login'),
		array('type' => 'dir', 'path' => 'data/upload/shop/member'),
		array('type' => 'dir', 'path' => 'data/upload/shop/membertag'),
		array('type' => 'dir', 'path' => 'data/upload/shop/pointprod'),
		array('type' => 'dir', 'path' => 'data/upload/shop/rec_position'),
		array('type' => 'dir', 'path' => 'data/upload/shop/refund'),
		array('type' => 'dir', 'path' => 'data/upload/shop/store'),
		array('type' => 'dir', 'path' => 'data/upload/shop/voucher'),
		array('type' => 'dir', 'path' => 'data/upload/shop/watermark'),
		array('type' => 'dir', 'path' => 'data/upload/circle'),
		array('type' => 'dir', 'path' => 'data/upload/cms'),
		array('type' => 'dir', 'path' => 'data/upload/microshop'),
		//array('type' => 'dir', 'path' => 'shop/install'),
);

$func_items = array(
		array('name' => 'mysql_connect'),
		array('name' => 'fsockopen'),
		array('name' => 'gethostbyname'),
		array('name' => 'file_get_contents'),
		array('name' => 'mb_convert_encoding'),
		array('name' => 'json_encode'),
);